baseURL = ""
languageCode = "en-us"
title = "TEXT"

publishDir = "docs"
paginate = "10"

theme = "mainroad"
googleAnalytics = "G-TXG7TQMK90"

[Params]
customJS = ["//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"] # Include custom JS files

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]


[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]